import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import { describe, expect, it } from "vitest";

const frontendRoot = process.cwd();
const sourcePath = resolve(
  frontendRoot,
  "openapi/accountshield.openapi.json",
);
const generatedPaths = [
  resolve(
    frontendRoot,
    "src/generated/accountshield/openapi-types.ts",
  ),
  resolve(
    frontendRoot,
    "src/generated/accountshield/openapi-client.ts",
  ),
] as const;

function sourceHash(): string {
  return createHash("sha256")
    .update(readFileSync(sourcePath, "utf8"))
    .digest("hex");
}

describe("generated OpenAPI artifacts", () => {
  it("records deterministic generator and source provenance", () => {
    const expectedHash = sourceHash();

    for (const path of generatedPaths) {
      const content = readFileSync(path, "utf8");
      expect(content).toContain(
        "Generated by accountshield-openapi-generator@1.0.0.",
      );
      expect(content).toContain(
        "Source: openapi/accountshield.openapi.json",
      );
      expect(content).toContain(`Source SHA-256: ${expectedHash}`);
      expect(content).toContain("DO NOT EDIT");
    }
  });

  it("contains no environment host, credential or browser-storage value", () => {
    const forbiddenPatterns = [
      /https?:\/\//i,
      /localhost/i,
      /127\.0\.0\.1/,
      /ACCOUNTSHIELD_API_URL/,
      /NEXT_PUBLIC_/,
      /Bearer\s+/i,
      /localStorage/,
      /sessionStorage/,
      /document\.cookie/,
    ] as const;

    for (const path of generatedPaths) {
      const content = readFileSync(path, "utf8");
      for (const pattern of forbiddenPatterns) {
        expect(content).not.toMatch(pattern);
      }
    }
  });
});
